name: ${project.name}
version: ${project.version}
description: ${plugin.description}
author: ${plugin.author}
website: ${plugin.url}
api-version: 1.16

main: ${plugin.mainClass}

commands:
  test:

permissions: {}